name: Playwright Tests

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm install

      - name: Install OS dependencies for Playwright
        run: npx playwright install-deps

      - name: Download Playwright browsers
        run: npx playwright install

      - name: Build the project
        run: npm run build

      - name: Start Next.js server
        run: npm run start &

      - name: Wait for server to be active
        run: npx wait-on http://localhost:3000

      - name: Run Playwright tests
        run: npx playwright test